apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotstar-clone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hotstar-clone
  template:
    metadata:
      labels:
        app: hotstar-clone
    spec:
      containers:
        - name: hotstar-clone
          image: 892334471137.dkr.ecr.ap-south-1.amazonaws.com/hotstar-clone:IMAGE_TAG
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"